### ISSUE TITLE
Working example?

### ISSUE THREAD

**Issue by jmcpeak** [facebook/fixed-data-table#114]
I have been trying to get FixedDataTable up and working in jsfiddle. I have searched or examples on both codepen, jsfiddle, jsbin, etc - no luck.

This fiddle should work - it does work with Hello World in React.

http://jsfiddle.net/jmcpeak/98b5qvzo/

Any help gettig it working so it can be added to the project?

**Comment by pieterv** [comment]
Hey @jmcpeak, hmm i think the order of requires is wrong in that fiddle which is throwing it off. I tired getting the project working in jsfiddle a while back but i couldn't get it easily setup due to the need for the object.assign polyfill before defining the table, but this should be easier in the next version of the table where this is not needed. I did setup the project with jsbin which has been working well for me: http://jsbin.com/valoco/10/edit?html,js,output
