### ISSUE TITLE
When headerDataGetter() returns null, respect label then

### ISSUE THREAD

**Issue by binarykitchen** [facebook/fixed-data-table#134]
I have a table here, using the `headerDataGetter()` to adjust the table headers for some special cases on some but not all columns.

For the other columns I want to specify the header text through a label as usual but this does not seem to work. Having a `headerDataGetter()` seems to ignore ALL labels, unfortunately.

**Comment by ehzhang** [comment]
This definitely seems like a good behavior to have, and we'll make note of it for our next release. In the meantime, you can calculate the header text using another function, as you are given the column index. Otherwise, you may be interested in applying a custom headerRenderer for the columns in question.

**Comment by binarykitchen** [comment]
This should be possible and easy to implement.

**Comment by ehzhang** [comment]
Indeed, this is indeed very possible and not very difficult to implement. However, with any change in the behavior of the table, we need to make sure to check our internal uses to make sure that it doesn't break anything before we sync it up with the public repo, and report changes. Thank you for your patience.

**Comment by ehzhang** [comment]
This has been fixed for version v0.4.0.
