### ISSUE TITLE
Can't use flexGrow and resizable columns simultaneously

### ISSUE THREAD

**Issue by michaelcarter-wf** [facebook/fixed-data-table#16]
Seems like if you specify a `flexGrow` constant and `isResizeable` on the same column, it should respect the flexGrow constant until the column is resized for the first time. Right now it just causes columns not to resize properly.

**Comment by liamcmitchell** [comment]
The current code as I understand it:
- final col width is calculated from `Table:width`, `Column:width` and `Column:flexGrow`
- `flexGrow` isn't set to 0 after resize, like it says in the docs
- when resizing, col width state is meant to be handled by the table's parent component
- there is no `onColumnResizeStartCallback` so no way to set `isColumnResizing` to true
Let me know if I have any of that wrong.

The problem comes from using the same `width` property to set exact width after resize and as a base for `flexGrow` calculation. This could be fixed in the parent component by working out flex values there but I would rather have both flex and resize state managed within `Table`. Managing resize state internally would make it a lot easier to use out of the box.

If you wanted to support managing resize state both internally and externally, then it might be easier to have both `width` and `defaultWidth` like input components. Use `width` for specifying exact width if you are managing width in the parent component or use `defaultWidth` as a base for internal resize state and flex calculations.

Any thoughts?

**Comment by matrinox** [comment]
I like the `width`/`defaultWidth` idea. Makes it clear your intent, maybe even a warning thrown when using `width` with `isResizable`

For now, I just set `flexGrow` to `null` which makes sense. I think explicitly setting `flexGrow` to `null` has clearer intent, too

**Comment by jdhenckel** [comment]
After two hours messing with this, here's what i found. 1. you MUST set columnMode=flex, 2. you set the flexGrow to a positive number, 3. the minWidth is useful, 4. the maxWidth and width values are IGNORED. 5. you might want to stretch the table, for instance class="material fullscreen", or some class of your own.
