### ISSUE TITLE
Select a table row?

### ISSUE THREAD

**Issue by aphillipo** [facebook/fixed-data-table#189]
Hi,

Any idea how I select a single or multiple table row with something like this in react?  

I think that it might be helpful if certain data properties can be translated to attributes or added to the classlist?  That way changing the state of the data is all that is needed to handle this.

For example I suppose we could just prefix a rows column or add an attributes object if required to each row...?

var rows = [
  ['a1', 'b1', 'c1', {attributes: { className: 'selected' }],
  ['a2', 'b3', 'c2'],
  ['a3', 'b3', 'c3'],
  ..... /// and more
];

Attributes for more complex examples of tables rows and implementations could work too?  Maybe call it rowAttributes?

I'd probably choose to keep a reference to any selected rows so I could clear them easily.

Ta.

**Comment by ehzhang** [comment]
Hi!

I would recommend keeping a selected property in your data itself. FixedDataTable is meant to render whatever data you provide. Selection state can be managed by a cellRenderer you provide. Likewise, changing selection state should be managed by the component that you provide the cellRenderer.

Because of this, I don't think that this would be a good change for the API, since it is up to you to manage the state of your individual components through components that you define, and data that you provide.

**Comment by aphillipo** [comment]
Ah okay so it's already going to get passed to cell renderer, of course that makes sense...
