### ISSUE TITLE
Suggestion: Inline-editing

### ISSUE THREAD

**Issue by Siyfion** [facebook/fixed-data-table#190]
I couldn't find any other mention of this, so I just thought I'd create an issue to track this....

Is inline-editing something that could be added in a later version? I imagine a lot of people would find it useful, especially with the recently announced official support in Meteor, inline-editing, reactive tables would be very cool!

**Comment by ehzhang** [comment]
Hi! Thanks for the suggestion. Unfortunately, this feature is outside of the scope of the table - you must provide the table with data and components, and how you manage that data is up to you! The table otherwise takes care of virtualizing the rows to maintain high performance scrolling. 

This decision keeps the table flexible enough to allow you to choose whatever you'd like to go in the cell, so you can adjust it to your use case. 

If you would like inline-editing, you can look into creating a component that does that by using cellRenderer and cellDataGetter.

**Comment by Siyfion** [comment]
Thanks for the quick response @ehzhang! While I think it's a shame that it's not something that would be officially supported, at least you have given us enough tools to write something to do it ourselves.

**Comment by ehzhang** [comment]
You're welcome :)

I'll be closing this issue now, but if you feel the need you can re-open it. Thanks!

**Comment by Siyfion** [comment]
@ehzhang Would I be able to use the `cellRenderer` and/or `cellDataGetter` to attach X-Editable (http://vitalets.github.io/x-editable/) to the contents such that when the data changed the X-Editable was reinitialised or whatever? Sorry if it's a dumb question, I'm only looking into React for the first time, so I'm not sure how it all ties together at the moment.

**Comment by ehzhang** [comment]
@Siyfion sorry for not seeing this sooner! Looking through the link you provided, I don't anticipate too much issue in terms of rendering if you used the inline version, but you'd probably have trouble with the pop-over. Also, because of the way that cells are routinely destroyed/rerendered, it may actually be a bit tricky to actually initialize each row with jQuery.

**Comment by Siyfion** [comment]
Hmm... as I thought! Hence why I was asking whether it was something you guys might think about supporting :tongue:

**Comment by Siyfion** [comment]
@ehzhang Perhaps an example could be added to the example list with a cell that has a simple numeric input, with two-way updates/bindings, just to show people how it could be done?
