### ISSUE TITLE
headerHeight & rowHeight: Must be used with attribute expressions?

### ISSUE THREAD

**Issue by gsklee** [facebook/fixed-data-table#21]
Found that I must use headerHeight & rowHeight with attribute expressions:

Won't Work:
```<Table width="1000" height="500" headerHeight="50" rowHeight="50" rowGetter={rowGetter} rowsCount={this.state.data.length}>```

Works:
```<Table width="1000" height="500" headerHeight={50} rowHeight={50} rowGetter={rowGetter} rowsCount={this.state.data.length}>```

Is this bug or intentional?

**Comment by pieterv** [comment]
This is intentional, when you don't use attribute expressions the number gets passed through as a string which means we could have weird side effects when doing basic math operations for example `10 + '5' = '105'`. When in dev mode you should be getting a nice error about this from the propTypes checks.

**Comment by gsklee** [comment]
@pieterv Great explanation, thanks!
