### ISSUE TITLE
Performance of FixedDataTable

### ISSUE THREAD

**Issue by gappture** [facebook/fixed-data-table#227]
I have 5 different FixedDataTables implemented in my interface where each has between 4-40 rows. However, I am running into some performance issues when using these tables. More specifically, I am noticing that scroll performance is very poor and that re-rendering these tables seems to be a very heavy operation that is slowing down the rest of my UI. 

I have identified the following potential sources for the poor performance:
   - The cellRender function is called hundreds/thousands of times when scrolling. My implementation of this method is shown in the attached image.
   - By using the Perf tool (https://facebook.github.io/react/docs/perf.html) in react I have noticed that there is significant "wasted time" when re-rendering these tables; a screenshot containing a summary of the output is provided.
<img width="485" alt="screen shot 2015-08-04 at 10 45 09" src="https://cloud.githubusercontent.com/assets/9976658/9056838/0dcc5bb8-3a96-11e5-91c7-7bf5a9e78013.png">
<img width="2275" alt="screen shot 2015-08-04 at 10 35 59" src="https://cloud.githubusercontent.com/assets/9976658/9056842/0fb72548-3a96-11e5-858f-be2144863798.png">

**Comment by ehzhang** [comment]
Hey @gappture! 
The cellRenderer should only fire when the results from either the rowGetter changes for a specific rowIndex or the results from the cellDataGetter changes. If the information you provide there changes often, that might be the source of these hundreds/thousands of renders.

Otherwise, your cellRenderer appears to be fairly straightforward.

I'd like to hear more about how you're using this, in case that sheds more light to this performance problem.

**Comment by gappture** [comment]
Thanks for your response! The rowGetter function seems to also be called hundreds/thousands of times depending on the amount of scrolling that takes place, this many calls to the rowGetter doesn't seem very efficient or is this supposed to happen? The implementation of my rowGetter is also very simple (see the screenshot) and the props that are used in the getter doesn't change very often.

What I am especially worried about is the "wasted time" rendering these tables. The React documentation states: ' "Wasted" time is spent on components that didn't actually render anything, e.g. the render stayed the same, so the DOM wasn't touched.' 

Do you experience a lot of "wasted time" when using the table component in your implementation or does this seem to be a problem specific to my implementation. 

If you wish to view my implementation of the table API I could send you my source code, perhaps you can find the performance bottleneck.

<img width="452" alt="screen shot 2015-08-04 at 14 06 08" src="https://cloud.githubusercontent.com/assets/9976658/9060330/f68ef376-3ab2-11e5-913a-a7721c760355.png">

**Comment by ehzhang** [comment]
@gappture 
It's actually not unusual, but actually expected for the rowGetter to fire many times - it's actually really fast. The problem is when the return value does not evaluate as true for otherwise equivalent information, which makes the table think - "oh hey, something's changed - we should rerender!"

In your rowGetter, you create a new data array every time the function is called. Unfortunately, this means that when we check the previous value, javascript does not think that it's equal, even if the data is the 'same'.

You can see for yourself by typing into the javascript console something like:
```
[1, 2, 3] ==  [1, 2, 3]
> false
```

Thanks, javascript :P

Instead, you'll want something that we can use to evaluate as true, like a reference to the original data. If your `this.props.data[rowIndex+1]` is an array, you might be able to solve your problem by changing your code to

```
_rowgetter: function(rowIndex){
  return this.props.data[rowIndex+1];
}
```

**Comment by gappture** [comment]
Thank you so much for your help! The table is more responsive now.

**Comment by ehzhang** [comment]
Glad to hear it :)
