### ISSUE TITLE
error when using 0.4.3 with webpack

### ISSUE THREAD

**Issue by chrisdrackett** [facebook/fixed-data-table#239]
I'm getting the following when running webpack:

`Module not found: Error: Cannot resolve module 'react-for-atom' in /Users/cwd/src/AnswerDash/Qazzow/sales_dashboard/node_modules/fixed-data-table/internal`

**Comment by ehzhang** [comment]
This arose while trying to add support for atom. You can safely ignore this error though. Otherwise, you may wish to revert back to 0.4.2 (the only difference is that)

**Comment by chrisdrackett** [comment]
yeah, I'm on 0.4.2 as it stops my build on 0.4.3.

**Comment by ehzhang** [comment]
I"m sorry about that :( I'm going to try and release a patch to 0.4.3 as soon as possible.

**Comment by YoYuUm** [comment]
I also get an error after the bundle is ready in webpack:

```
ERROR in ./~/fixed-data-table/~/react-for-atom/main.js
Module parse failed: /deck/node_modules/fixed-data-table/node_modules/react-for-atom/main.js Line 28: Unexpected token )
You may need an appropriate loader to handle this file type.
|     var addons;
|     Object.defineProperty(React, 'addons', {
|       get() {
|         if (!addons) {
|           React = require('react/addons');
 @ ./~/fixed-data-table/internal/React.js 18:10-35
```

I'm currently running 0.4.4

**Comment by AlesJiranek** [comment]
I get same error with webpack and 0.4.4

**Comment by ehzhang** [comment]
@AlesJiranek @YoYuUm I can't seem to reproduce this error on my end - 0.4.4 builds using webpack without error for me. Are you using the provided webpack config or your own?

If this continues to be an error, I may have to roll back these changes in the next release. :\

**Comment by SupremeTechnopriest** [comment]
@ehzhang I am also seeing this using my own webpack config. See below:

```
/**
 * Webpack Dev Config
 * react-hot-loader and babel
 *
 * @author  Randy Lebeau
 *
 */

var path = require('path');
var webpack = require('webpack');

module.exports = {
    devtool: 'eval',
    watch: true,
    cache: false,
    entry: [
        './examples/Init'
    ],
    resolve: {
        extensions: ['', '.jsx', '.js', '.scss', '.woff', '.ttf', '.eot', '.svg', '.otf'],
        modulesDirectories: ['src', 'node_modules']
    },
    output: {
        path: path.join(__dirname, 'examples', 'build'),
        filename: 'script.js',
        publicPath: '/'
    },
    plugins: [
        new webpack.NoErrorsPlugin()
    ],
    module: {
        loaders: [{
            test: /\.jsx?$/,
            loaders: ['react-hot', 'babel-loader'],
            exclude: path.join(__dirname, 'node_modules')
        }, {
            test: /\.json$/,
            loader: 'json-loader',
            include: path.join(__dirname, 'node_modules/moment-timezone')
        }, {
            test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
            loader: 'url-loader?limit=10000&mimetype=application/font-woff',
            include: path.join(__dirname, 'src/fonts')
        }, {
            test: /\.(ttf|eot|svg|otf)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
            loader: 'file-loader',
            include: path.join(__dirname, 'src/fonts')
        }, {
            test: /\.woff(2)?(\?ntbba6)?$/,
            loader: 'url-loader?limit=10000&mimetype=application/font-woff',
            include: path.join(__dirname, 'src/fonts')
        }, {
            test: /\.(ttf|eot|svg|otf)(\?ntbba6)?$/,
            loader: 'file-loader',
            include: path.join(__dirname, 'src/fonts')
        }]
    }
};
```

**Comment by AlesJiranek** [comment]
I'm using [este/este](https://github.com/este/este), so my config looks like https://github.com/este/este/blob/master/webpack/makeconfig.js

**Comment by HankMcCoy** [comment]
This breaks with my Webpack config. It looks like `react-for-atom` assumes the presence of [ES6 object method shorthand syntax](http://babeljs.io/docs/learn-es2015/#enhanced-object-literals), which is a fair guess in the context of Atom, but not in a browser. You have the `require` call within a conditional check, but at compile time Webpack doesn't know which way that conditional is going to go so it attempts to pull in both `react` and `react-for-atom`, resulting in the error.

I have no idea what the right way to support Atom as a platform would be, but this approach definitely results in problems for those of us attempting to use `fixed-data-table` in the browser environment via NPM/Webpack. I'd really prefer to not have to modify my existing Webpack config in order to get this working.

Momentary annoyances aside, my thanks to you and the rest of the contributors for your work on this project!

**Comment by ehzhang** [comment]
Hi everybody! Please update to the latest 0.4.5 version, which should fix these issues since we've basically reverted back.

The problems here arose from attempting to support react-for-atom within, and @HankMcCoy draws on the exact reasons why this was more than unfortunate. We're going to look for better ways of supporting Atom without affecting this library.

Sorry about this release hiccup!
