### ISSUE TITLE
Edit Table cells in-place

### ISSUE THREAD

**Issue by fullvlad** [facebook/fixed-data-table#249]
Is it possible to edit table cells in-place like in Excel?

If the answer is yes, how do you suggest me doing so?

Thanks in advance.

**Comment by pieterv** [comment]
Hey @fullvlad yes this is possible, at FB we have this functionality with FixedDataTable for one of our ads products. For something complex like this I would suggest connecting each cell to its data source directly, we do this via Flux, each cell connects to its data store based on the row index and binds to events which will set state on the cell (rather than passing the data back through the data getter).

**Comment by cosminnicula** [comment]
Can you please provide a code sample for this? Thanks.

**Comment by fullvlad** [comment]
@pieterv yes, some sample code would really be helpful, because I don't know how would I use the rowGetter function in this case and, also, how would I define a store to be mapped to a row (so that it has all the information for each column in that row), given that the table now is initialized by Columns.

**Comment by ehzhang** [comment]
@fullvlad you can use the cellRenderer to render the cells connected to your flux stores, and then use the rowGetter function to get the value in your store. The rowGetter when you do this will be used to decide rendering of the cells, and you don't have to use that data when you use the cellRenderer.

**Comment by fullvlad** [comment]
@ehzhang @pieterv so that would mean I'd have to have a separate store for each cell or for each column?

**Comment by fullvlad** [comment]
@ehzhang @pieterv I think your two answers don't represent the same idea. Either use `rowGetter` to get the data for each cell from its store, or use it just to _render_ the cell component, and its date will be taken from its store.

I'd really appreciate a thorough explanation :)
