### ISSUE TITLE
table footer (spanning all columns)

### ISSUE THREAD

**Issue by giogonzo** [facebook/fixed-data-table#282]
Hello, sorry if this has already been asked/discussed but couldn't find anything in the docs or other issues..

Is there a way to create a table footer, spanning all columns?

If not, any suggestion to obtain the behavior with current api?

**Comment by ehzhang** [comment]
Yes there is!

Use the `footerHeight` and `footerDataGetter` properties in the `Table` and for your columns, optionally specify a `footerRenderer`.

The footer is fixed on the bottom, and span all of the columns.

**Comment by giogonzo** [comment]
Oh, thanks!

still, I'm confused: ideally, I'd want to have a `footerRenderer` at the table level, i.e. rendering a sticky footer with data not necessarily per-column.

My use case now would be: show additional data on a selected row only when the row is selected, otherwise show nothing (no footer)

I know there are ways to do this outside of FDT easily, e.g. by rendering a component in overlay or rendering a component right below the table, and then resize table in height.
Both approaches have drawbacks though (either you hide part of the scroll area with first solution, or you have to manually resize the table in height with the second)

Am I missing something?

**Comment by ehzhang** [comment]
The table doesn't support a footer at the table level - to get that kind of functionality, you can show/hide the footer by changing the `footerHeight` from 0 to your value.

However, it sounds like your first idea would be totally reasonable - that is, rendering a component that is absolutely positioned and overlays the bottom of the table. I don't think that the drawback there is significant, since that is how the fixed footer behaves in the first place.

**Comment by giogonzo** [comment]
Ok, thanks for your input here - I'll try it and come back here if anything interesting comes out

Thanks!
