### ISSUE TITLE
Use default scrollbar without specifying height or maxHeight

### ISSUE THREAD

**Issue by llh1** [facebook/fixed-data-table#60]
Hi all!

Thanks for your work on FixedDataTable.

Currently, it's mandatory to provide a height or a maxHeight to the Table component. I was wondering what's the reason for making this parameter mandatory? Then, is it possible to flatten the table so all the data are displayed on the page using the default scrollbar of the page? 

For now, when I have a lot of data which takes more place than the specified table height, a scrollbar appears for the table container. I'd like to display all the data on the page, and use the normal scrollbar.

Any advices? 

Thanks

**Comment by ofersadgat** [comment]
The reason that the table requires the size parameter is because it uses the fixed size to remove elements from the DOM that arent displayed on screen.

In order to do this the way that you want, you would have to hook window.onScroll, use that to update the dom by finding the visible region of the screen and then rendering just that section using absolute positioning. While that might be a good feature to add in the future, as I have hopefully illustrated, it is a lot of work.

**Comment by llh1** [comment]
Right, thanks for your answer :)
