### ISSUE TITLE
[Site] /assets/main.js is not minified

### ISSUE THREAD

**Issue by Daniel15** [facebook/fixed-data-table#8]
http://facebook.github.io/fixed-data-table/assets/main.js is pretty large and currently unminified. Ideally it should be minified, served with a far-future expires header, and have a cache-busting hash in the URL :)

**Comment by pieterv** [comment]
+1 I had this enabled but had to disable it as it was breaking the diff between client and server rendering since the html string generated from the markdown was getting modified, i will look at this when i get a chance. As for headers, i dont believe we have the option to set these from gh-pages hosting.

**Comment by Daniel15** [comment]
In that case you could probably pull the Markdown into a separate bundle that's not minified. Also React should be loaded from the CDN rather than being bundled.

**Comment by pieterv** [comment]
I have added the minification and file hashing. It took some serous webpack digging to work out that it applies an html minifier which is enable when you add the uglify plugin, this was causing the differences between the node and client React outputs.

I don't really think loading React from a CDN is worth the complexity it would add for this site so im going to close this issue out for now, we can address it again if this because an issue.

**Comment by pieterv** [comment]
This change is now live, the bundle is a lot smaller now.

Thanks for the issue!

**Comment by Daniel15** [comment]
Awesome, thanks Pieter! :D
